heat_template_version: 2018-03-02

description: >
  A template to deploy two Ubuntu Server instances,
  each with 1 vCPU and 3GB RAM.

parameters:
  image_ubuntu:
    type: string
    description: Name or ID of the Ubuntu image to use
    default: Ubuntu Server 24.04 LTS (Noble Numbat) amd64

  flavor:
    type: string
    description: Flavor with 1 CPU and 4GB RAM
    default: gx3.1c3r

  security_group:
    type: string
    description: Name of the security group to attach to the instances
    default: infrastructure-delivery-pipeline-security-group

resources:
  # Creating the Network
  my_network:
    type: OS::Neutron::Net
    properties:
      name: infrastructure-delivery-pipeline-network

  # Subnet for the network
  my_subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: my_network }
      cidr: 192.168.1.0/24
      ip_version: 4

  # Creating the Frontend Linux Instance
  frontend_instance:
    type: OS::Nova::Server
    properties:
      name: FrontendServer
      image: { get_param: image_ubuntu }
      flavor: { get_param: flavor }
      networks:
        - network: { get_resource: my_network }
      key_name: infrastructure-delivery-pipeline-key-pair
      security_groups: [{ get_param: security_group }]
    depends_on: my_network

  # Creating the Backend Linux Instance
  backend_instance:
    type: OS::Nova::Server
    properties:
      name: BackendServer
      image: { get_param: image_ubuntu }
      flavor: { get_param: flavor }
      networks:
        - network: { get_resource: my_network }
      key_name: infrastructure-delivery-pipeline-key-pair
      security_groups: [{ get_param: security_group }]
    depends_on: my_network

outputs:
  frontend_instance_ip:
    description: IP address of the Frontend Server
    value: { get_attr: [frontend_instance, first_address] }

  backend_instance_ip:
    description: IP address of the Backend Server
    value: { get_attr: [backend_instance, first_address] }
