name: Update OpenStack Stack and Deploy Application

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'backend/**'
      - 'frontend/**'
  workflow_dispatch:

jobs:
  # Linting and Validation Job
  lint_and_validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install yamllint
      - name: Install yamllint
        run: pip install yamllint

      # Run YAML Linting
      - name: Run YAML Linting
        run: yamllint template.yaml

      # Validate JSON Files using jq (pre-installed on ubuntu-latest)
      - name: Validate JSON Files
        run: |
          jq empty backend/package.json
          jq empty frontend/package.json

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install and Run ESLint in Backend
      - name: Install and Run ESLint in Backend
        working-directory: backend
        run: |
          npm install
          npm run lint

      # Install and Run ESLint in Frontend
      - name: Install and Run ESLint in Frontend
        working-directory: frontend
        run: |
          npm install
          npm run lint

  # Backend Test Suite
  backend_test_suite:
    runs-on: ubuntu-latest
    needs: lint_and_validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Cache dependencies
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      # Install Backend Dependencies
      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      # Run Backend Unit Tests
      - name: Run Backend Unit Tests
        working-directory: backend
        run: npm run test:unit

      # Run Backend Integration Tests
      - name: Run Backend Integration Tests
        working-directory: backend
        run: npm run test:integration

  # Frontend Test Suite
  frontend_test_suite:
    runs-on: ubuntu-latest
    needs: lint_and_validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Cache dependencies
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      # Install Frontend Dependencies
      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      # Run Frontend E2E Tests
      - name: Run Frontend E2E Tests
        working-directory: frontend
        run: npm run test:e2e

  # Configure OpenStack
  configure_openstack:
    runs-on: ubuntu-latest
    needs: [backend_test_suite, frontend_test_suite]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install OpenStack CLI tools
      - name: Install OpenStack CLI tools
        run: pip install python-openstackclient python-heatclient

      # Configure OpenStack Environment and Update Stack
      - name: Update OpenStack Stack
        env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_PROJECT_DOMAIN_ID: ${{ secrets.OS_PROJECT_DOMAIN_ID }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_IDENTITY_API_VERSION: ${{ secrets.OS_IDENTITY_API_VERSION }}
          OS_INTERFACE: ${{ secrets.OS_INTERFACE }}
        run: |
          openstack stack update --existing --template template.yaml infrastructure-delivery-pipeline-stack

  # Deploy Backend
  deploy_backend:
    runs-on: ubuntu-latest
    needs: configure_openstack
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Start SSH Agent and Add SSH Key
      - name: Start SSH Agent and Add Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PEM_KEY }}

      # Deploy Backend Application
      - name: Deploy Backend to Backend Instance
        env:
          BACKEND_IP_ADDRESS: ${{ secrets.BACKEND_IP_ADDRESS }}
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.BACKEND_IP_ADDRESS }} << 'EOF'
            # Kill any existing process on port 8080
            if lsof -t -i:8080; then
              sudo kill -9 $(lsof -t -i:8080)
            fi

            # Remove and recreate the backend directory
            rm -rf /home/ubuntu/backend
            mkdir -p /home/ubuntu/backend
          EOF
          
          # Copy backend files to the server
          scp -o StrictHostKeyChecking=no -r ./backend/* ubuntu@${{ env.BACKEND_IP_ADDRESS }}:/home/ubuntu/backend
          
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.BACKEND_IP_ADDRESS }} << 'EOF'
            # Install Node.js 18
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs

            # Install dependencies and start backend server
            cd /home/ubuntu/backend
            npm install
            nohup node app.js > /home/ubuntu/backend-server.log 2>&1 &
          EOF

  # Deploy Frontend
  deploy_frontend:
    runs-on: ubuntu-latest
    needs: configure_openstack
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Start SSH Agent and Add SSH Key
      - name: Start SSH Agent and Add Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PEM_KEY }}

      # Deploy Frontend Application
      - name: Deploy Frontend to Frontend Instance
        env:
          FRONTEND_IP_ADDRESS: ${{ secrets.FRONTEND_IP_ADDRESS }}
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.FRONTEND_IP_ADDRESS }} << 'EOF'
            # Kill any existing process on port 8080
            if lsof -t -i:8080; then
              sudo kill -9 $(lsof -t -i:8080)
            fi

            # Remove and recreate the frontend directory
            rm -rf /home/ubuntu/frontend
            mkdir -p /home/ubuntu/frontend
          EOF
          
          # Copy frontend files to the server
          scp -o StrictHostKeyChecking=no -r ./frontend/* ubuntu@${{ env.FRONTEND_IP_ADDRESS }}:/home/ubuntu/frontend
          
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.FRONTEND_IP_ADDRESS }} << 'EOF'
            # Install Node.js 18
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs

            # Install dependencies and start frontend server
            cd /home/ubuntu/frontend
            npm install
            nohup node frontend-server.js > /home/ubuntu/frontend/frontend-server.log 2>&1 &
          EOF
