name: Update OpenStack Stack and Deploy Frontend

on:
  push:
    branches:
      - main  # Run on changes to the main branch (adjust if needed)
    paths:
      - 'template.yaml'  # Only trigger when this file is changed
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update_stack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Upgrade OpenStack CLI and Heat Client
        run: |
          sudo apt update
          sudo apt install -y python3-openstackclient
          sudo apt install -y python3-pip
          pip install --upgrade pip
          pip install --upgrade python-openstackclient python-heatclient

      - name: Debug Python Version and Installed Packages
        run: |
          python3 --version
          pip3 list

      - name: Debug Environment Variables
        run: printenv

      - name: Configure OpenStack Environment
        env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_PROJECT_DOMAIN_ID: ${{ secrets.OS_PROJECT_DOMAIN_ID }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_IDENTITY_API_VERSION: ${{ secrets.OS_IDENTITY_API_VERSION }}
          OS_INTERFACE: ${{ secrets.OS_INTERFACE }}
        run: |
          export OS_AUTH_URL=$OS_AUTH_URL
          export OS_PROJECT_NAME=$OS_PROJECT_NAME
          export OS_USERNAME=$OS_USERNAME
          export OS_PASSWORD=$OS_PASSWORD
          export OS_REGION_NAME=$OS_REGION_NAME
          export OS_USER_DOMAIN_NAME=$OS_USER_DOMAIN_NAME
          export OS_PROJECT_DOMAIN_ID=$OS_PROJECT_DOMAIN_ID
          export OS_PROJECT_ID=$OS_PROJECT_ID
          export OS_IDENTITY_API_VERSION=$OS_IDENTITY_API_VERSION
          export OS_INTERFACE=$OS_INTERFACE

      - name: Update OpenStack Stack
        env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_PROJECT_DOMAIN_ID: ${{ secrets.OS_PROJECT_DOMAIN_ID }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_IDENTITY_API_VERSION: ${{ secrets.OS_IDENTITY_API_VERSION }}
          OS_INTERFACE: ${{ secrets.OS_INTERFACE }}
        run: |
          openstack stack update --existing --template template.yaml infrastructure-delivery-pipeline-stack

      - name: Deploy Frontend to Windows Instance
        env:
          WINDOWS_IP_ADDRESS: ${{ secrets.WINDOWS_IP_ADDRESS }}
        run: |
          scp -i C:\Users\simon\OneDrive\Skolearbeid\NTNU\5. Semester\Administrasjon av Skytjeneseter\Portfolio\infrastructure-delivery-pipeline-key-pair.pem ./frontend/index.html windows@${{ env.WINDOWS_IP_ADDRESS }}:C:/xampp/htdocs/index.html
